### PR TITLE
messaging partone done!

### PR DESCRIPTION
**Pull request by rajayarli**

### CODE REVIEW

**Comment by Kachi-Okorie** [comment]
Looked at the code and the nav bar area is not fixed

**Review by Kachi-Okorie — CHANGES_REQUESTED** [review]
Navbar CSS needs to be investigated.

**Review by rajayarli — COMMENTED** [review]
okay

**Review by rajayarli — COMMENTED** [review]
okay

**Comment by DaGoblin** [comment]
Looks ok now I don't think I can approve while you have changes requested

**Review by DaGoblin — APPROVED** [review]
Looks ok and displayed correctly when i can the code.

**Pull request closed without merging**
